# Generated by Django 5.2.1 on 2025-05-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('rating', models.FloatField()),
                ('sold_count', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('category', models.CharField(choices=[('PLANTS', 'Plants'), ('SEEDS', 'Seeds'), ('FERTILIZERS', 'Fertilizers'), ('PESTICIDES', 'Pesticides')], max_length=20)),
            ],
        ),
    ]
