# Generated by Django 5.2.1 on 2025-05-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold_count',
        ),
    ]
